### ISSUE TITLE
react.production.js and ink.es2015.js produce namespace collisions when included simultaneously

### ISSUE THREAD

**Issue by furkle** [y-lohse/inkjs#466] opened 2020-04-19 21:56 UTC
## Overview
A frequent use case for those who use inkjs is to combine it with React for componenting and reactive updates. However, I and at least one other user have found that with a new React bundle, and the current version of the ES Modules bundle, a namespace collision occurs, as both try to define the `window` property `e` in strict mode. My workaround at present is to load the TypeScript `Story` file instead, but this feels like an issue which may be solvable.

The obvious answer seemed to be to import the CommonJS module at `dist/ink.js`, but my experience is that webpack/ES Modules setups very much prefer not to mix CJS and ESM, and it would be preferable if we were obligated to consume neither the CJS nor TS files.

## Reproduction
1. Produce a new React app with `create-react-app`.
1. Install `inkjs` through `npm`.
1. Import `inkjs` and use one of its exports in one of your compiled JS/TS files.
1. Try to build the file. Note that this error does _not_ occur in development mode, likely because the global properties defined by React in development mode are not mangled, and therefore do not collide with inkjs' `e`. You should see an error with defining an already defined variable `e`.

**Comment by y-lohse** [comment] 2020-04-20 09:16
This is a duplicate of #427 so I'll close this issue and reply other there.

**Closed by y-lohse** 2020-04-20 09:16 UTC
