### ISSUE TITLE
Couldnʻt get 2.2.3 or 2.2.4 working..

### ISSUE THREAD

**Issue by kalani96746** [y-lohse/inkjs#1075] opened 2024-08-03 06:13 UTC
..and I had to add this to the ink.d.ts file to get 2.2.2 to work.
import issues with the others and the typeof gets in the way in the d.ts.

let Story = Story;
let InkList = InkList;
let Compiler = Compiler;
let CompilerOptions = CompilerOptions;
let PosixFileHandler = PosixFileHandler;
let JsonFileHandler = JsonFileHandler;

export {Story, InkList, Compiler, CompilerOptions, PosixFileHandler, JsonFileHandler};

**Comment by smwhr** [comment] 2024-08-03 10:01
Closed as duplicate of https://github.com/y-lohse/inkjs/issues/1065

**Closed by smwhr** 2024-08-03 10:01 UTC
